service:
  name: aws-stift-und-block
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect
  dice:
    handler: handler.dice
    events:
      - websocket:
          route: $default

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
